# Do not run this workflow on pull request since this workflow has permission to modify contents.
on:
  push:
    branches:
      - main

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write
  # pull request permission to comment on pull requests
  pull-requests: write

jobs:
  benchmark:
    name: Testing ground benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Kosmos metrics / tiger board
          benchmark-data-dir-path: kosmos/wakanda/tiger
          tool: 'customSmallerIsBetter'
          output-file-path: metrics.json
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: false
          # Enable Job Summary for PRs
          summary-always: true
          comment-always: true
