# Do not run this workflow on pull request since this workflow has permission to modify contents.
on:
  push:
    branches:
      - main

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write
  # pull request permission to comment on pull requests
  pull-requests: write

jobs:
  code_size:
    uses: Logitech/cpg-test_metrics/.github/workflows/code_metrics.yml@main
    with:
      MAP_FILE: canova_app.map
      PROJECT_NAME: canova
      PROJECT_PLATFORM: hadron
    secrets:
      GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
