# Do not run this workflow on pull request since this workflow has permission to modify contents.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    name: Testing ground benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      # Run benchmark
      - name: Run benchmark
        run: python3 gen_test_results.py
      # gh-pages branch is updated and pushed automatically with extracted benchmark data
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Exemple Metrics
          tool: 'customSmallerIsBetter'
          output-file-path: test_results.json
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
          # Enable Job Summary for PRs
          summary-always: true
